/***************************************************************************
 *   Copyright(C)2009-2014 by Gorgon Meducer<Embedded_zhuoran@hotmail.com> *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#ifndef __MREPEAT_H__
#define __MREPEAT_H__

#include "./tpaste.h"


/*! \brief       This macro represents a horizontal repetition construct.
 *
 *  \param count The number of repetitious calls to macro. Valid values range from 0 to 512.
 *  \param macro A binary operation of the form macro(n, data). This macro is expanded by MREPEAT with
 *               the current repetition number and the auxiliary data argument.
 *  \param data  Auxiliary data passed to macro.
 *
 *  \return      <tt>macro(0, data) macro(1, data) ... macro(count - 1, data)</tt>
 */
#define MREPEAT(count, macro, data)     TPASTE2(MREPEAT, count)(macro, data)

#define MREPEAT0(  macro, data)
#define MREPEAT1(  macro, data)     MREPEAT0(  macro, data)   macro(  0, data)
#define MREPEAT2(  macro, data)     MREPEAT1(  macro, data)   macro(  1, data)
#define MREPEAT3(  macro, data)     MREPEAT2(  macro, data)   macro(  2, data)
#define MREPEAT4(  macro, data)     MREPEAT3(  macro, data)   macro(  3, data)
#define MREPEAT5(  macro, data)     MREPEAT4(  macro, data)   macro(  4, data)
#define MREPEAT6(  macro, data)     MREPEAT5(  macro, data)   macro(  5, data)
#define MREPEAT7(  macro, data)     MREPEAT6(  macro, data)   macro(  6, data)
#define MREPEAT8(  macro, data)     MREPEAT7(  macro, data)   macro(  7, data)
#define MREPEAT9(  macro, data)     MREPEAT8(  macro, data)   macro(  8, data)
#define MREPEAT10( macro, data)     MREPEAT9(  macro, data)   macro(  9, data)
#define MREPEAT11( macro, data)     MREPEAT10( macro, data)   macro( 10, data)
#define MREPEAT12( macro, data)     MREPEAT11( macro, data)   macro( 11, data)
#define MREPEAT13( macro, data)     MREPEAT12( macro, data)   macro( 12, data)
#define MREPEAT14( macro, data)     MREPEAT13( macro, data)   macro( 13, data)
#define MREPEAT15( macro, data)     MREPEAT14( macro, data)   macro( 14, data)
#define MREPEAT16( macro, data)     MREPEAT15( macro, data)   macro( 15, data)
#define MREPEAT17( macro, data)     MREPEAT16( macro, data)   macro( 16, data)
#define MREPEAT18( macro, data)     MREPEAT17( macro, data)   macro( 17, data)
#define MREPEAT19( macro, data)     MREPEAT18( macro, data)   macro( 18, data)
#define MREPEAT20( macro, data)     MREPEAT19( macro, data)   macro( 19, data)
#define MREPEAT21( macro, data)     MREPEAT20( macro, data)   macro( 20, data)
#define MREPEAT22( macro, data)     MREPEAT21( macro, data)   macro( 21, data)
#define MREPEAT23( macro, data)     MREPEAT22( macro, data)   macro( 22, data)
#define MREPEAT24( macro, data)     MREPEAT23( macro, data)   macro( 23, data)
#define MREPEAT25( macro, data)     MREPEAT24( macro, data)   macro( 24, data)
#define MREPEAT26( macro, data)     MREPEAT25( macro, data)   macro( 25, data)
#define MREPEAT27( macro, data)     MREPEAT26( macro, data)   macro( 26, data)
#define MREPEAT28( macro, data)     MREPEAT27( macro, data)   macro( 27, data)
#define MREPEAT29( macro, data)     MREPEAT28( macro, data)   macro( 28, data)
#define MREPEAT30( macro, data)     MREPEAT29( macro, data)   macro( 29, data)
#define MREPEAT31( macro, data)     MREPEAT30( macro, data)   macro( 30, data)
#define MREPEAT32( macro, data)     MREPEAT31( macro, data)   macro( 31, data)
#define MREPEAT33( macro, data)     MREPEAT32( macro, data)   macro( 32, data)
#define MREPEAT34( macro, data)     MREPEAT33( macro, data)   macro( 33, data)
#define MREPEAT35( macro, data)     MREPEAT34( macro, data)   macro( 34, data)
#define MREPEAT36( macro, data)     MREPEAT35( macro, data)   macro( 35, data)
#define MREPEAT37( macro, data)     MREPEAT36( macro, data)   macro( 36, data)
#define MREPEAT38( macro, data)     MREPEAT37( macro, data)   macro( 37, data)
#define MREPEAT39( macro, data)     MREPEAT38( macro, data)   macro( 38, data)
#define MREPEAT40( macro, data)     MREPEAT39( macro, data)   macro( 39, data)
#define MREPEAT41( macro, data)     MREPEAT40( macro, data)   macro( 40, data)
#define MREPEAT42( macro, data)     MREPEAT41( macro, data)   macro( 41, data)
#define MREPEAT43( macro, data)     MREPEAT42( macro, data)   macro( 42, data)
#define MREPEAT44( macro, data)     MREPEAT43( macro, data)   macro( 43, data)
#define MREPEAT45( macro, data)     MREPEAT44( macro, data)   macro( 44, data)
#define MREPEAT46( macro, data)     MREPEAT45( macro, data)   macro( 45, data)
#define MREPEAT47( macro, data)     MREPEAT46( macro, data)   macro( 46, data)
#define MREPEAT48( macro, data)     MREPEAT47( macro, data)   macro( 47, data)
#define MREPEAT49( macro, data)     MREPEAT48( macro, data)   macro( 48, data)
#define MREPEAT50( macro, data)     MREPEAT49( macro, data)   macro( 49, data)
#define MREPEAT51( macro, data)     MREPEAT50( macro, data)   macro( 50, data)
#define MREPEAT52( macro, data)     MREPEAT51( macro, data)   macro( 51, data)
#define MREPEAT53( macro, data)     MREPEAT52( macro, data)   macro( 52, data)
#define MREPEAT54( macro, data)     MREPEAT53( macro, data)   macro( 53, data)
#define MREPEAT55( macro, data)     MREPEAT54( macro, data)   macro( 54, data)
#define MREPEAT56( macro, data)     MREPEAT55( macro, data)   macro( 55, data)
#define MREPEAT57( macro, data)     MREPEAT56( macro, data)   macro( 56, data)
#define MREPEAT58( macro, data)     MREPEAT57( macro, data)   macro( 57, data)
#define MREPEAT59( macro, data)     MREPEAT58( macro, data)   macro( 58, data)
#define MREPEAT60( macro, data)     MREPEAT59( macro, data)   macro( 59, data)
#define MREPEAT61( macro, data)     MREPEAT60( macro, data)   macro( 60, data)
#define MREPEAT62( macro, data)     MREPEAT61( macro, data)   macro( 61, data)
#define MREPEAT63( macro, data)     MREPEAT62( macro, data)   macro( 62, data)
#define MREPEAT64( macro, data)     MREPEAT63( macro, data)   macro( 63, data)
#define MREPEAT65( macro, data)     MREPEAT64( macro, data)   macro( 64, data)
#define MREPEAT66( macro, data)     MREPEAT65( macro, data)   macro( 65, data)
#define MREPEAT67( macro, data)     MREPEAT66( macro, data)   macro( 66, data)
#define MREPEAT68( macro, data)     MREPEAT67( macro, data)   macro( 67, data)
#define MREPEAT69( macro, data)     MREPEAT68( macro, data)   macro( 68, data)
#define MREPEAT70( macro, data)     MREPEAT69( macro, data)   macro( 69, data)
#define MREPEAT71( macro, data)     MREPEAT70( macro, data)   macro( 70, data)
#define MREPEAT72( macro, data)     MREPEAT71( macro, data)   macro( 71, data)
#define MREPEAT73( macro, data)     MREPEAT72( macro, data)   macro( 72, data)
#define MREPEAT74( macro, data)     MREPEAT73( macro, data)   macro( 73, data)
#define MREPEAT75( macro, data)     MREPEAT74( macro, data)   macro( 74, data)
#define MREPEAT76( macro, data)     MREPEAT75( macro, data)   macro( 75, data)
#define MREPEAT77( macro, data)     MREPEAT76( macro, data)   macro( 76, data)
#define MREPEAT78( macro, data)     MREPEAT77( macro, data)   macro( 77, data)
#define MREPEAT79( macro, data)     MREPEAT78( macro, data)   macro( 78, data)
#define MREPEAT80( macro, data)     MREPEAT79( macro, data)   macro( 79, data)
#define MREPEAT81( macro, data)     MREPEAT80( macro, data)   macro( 80, data)
#define MREPEAT82( macro, data)     MREPEAT81( macro, data)   macro( 81, data)
#define MREPEAT83( macro, data)     MREPEAT82( macro, data)   macro( 82, data)
#define MREPEAT84( macro, data)     MREPEAT83( macro, data)   macro( 83, data)
#define MREPEAT85( macro, data)     MREPEAT84( macro, data)   macro( 84, data)
#define MREPEAT86( macro, data)     MREPEAT85( macro, data)   macro( 85, data)
#define MREPEAT87( macro, data)     MREPEAT86( macro, data)   macro( 86, data)
#define MREPEAT88( macro, data)     MREPEAT87( macro, data)   macro( 87, data)
#define MREPEAT89( macro, data)     MREPEAT88( macro, data)   macro( 88, data)
#define MREPEAT90( macro, data)     MREPEAT89( macro, data)   macro( 89, data)
#define MREPEAT91( macro, data)     MREPEAT90( macro, data)   macro( 90, data)
#define MREPEAT92( macro, data)     MREPEAT91( macro, data)   macro( 91, data)
#define MREPEAT93( macro, data)     MREPEAT92( macro, data)   macro( 92, data)
#define MREPEAT94( macro, data)     MREPEAT93( macro, data)   macro( 93, data)
#define MREPEAT95( macro, data)     MREPEAT94( macro, data)   macro( 94, data)
#define MREPEAT96( macro, data)     MREPEAT95( macro, data)   macro( 95, data)
#define MREPEAT97( macro, data)     MREPEAT96( macro, data)   macro( 96, data)
#define MREPEAT98( macro, data)     MREPEAT97( macro, data)   macro( 97, data)
#define MREPEAT99( macro, data)     MREPEAT98( macro, data)   macro( 98, data)
#define MREPEAT100(macro, data)     MREPEAT99( macro, data)   macro( 99, data)
#define MREPEAT101(macro, data)     MREPEAT100(macro, data)   macro(100, data)
#define MREPEAT102(macro, data)     MREPEAT101(macro, data)   macro(101, data)
#define MREPEAT103(macro, data)     MREPEAT102(macro, data)   macro(102, data)
#define MREPEAT104(macro, data)     MREPEAT103(macro, data)   macro(103, data)
#define MREPEAT105(macro, data)     MREPEAT104(macro, data)   macro(104, data)
#define MREPEAT106(macro, data)     MREPEAT105(macro, data)   macro(105, data)
#define MREPEAT107(macro, data)     MREPEAT106(macro, data)   macro(106, data)
#define MREPEAT108(macro, data)     MREPEAT107(macro, data)   macro(107, data)
#define MREPEAT109(macro, data)     MREPEAT108(macro, data)   macro(108, data)
#define MREPEAT110(macro, data)     MREPEAT109(macro, data)   macro(109, data)
#define MREPEAT111(macro, data)     MREPEAT110(macro, data)   macro(110, data)
#define MREPEAT112(macro, data)     MREPEAT111(macro, data)   macro(111, data)
#define MREPEAT113(macro, data)     MREPEAT112(macro, data)   macro(112, data)
#define MREPEAT114(macro, data)     MREPEAT113(macro, data)   macro(113, data)
#define MREPEAT115(macro, data)     MREPEAT114(macro, data)   macro(114, data)
#define MREPEAT116(macro, data)     MREPEAT115(macro, data)   macro(115, data)
#define MREPEAT117(macro, data)     MREPEAT116(macro, data)   macro(116, data)
#define MREPEAT118(macro, data)     MREPEAT117(macro, data)   macro(117, data)
#define MREPEAT119(macro, data)     MREPEAT118(macro, data)   macro(118, data)
#define MREPEAT120(macro, data)     MREPEAT119(macro, data)   macro(119, data)
#define MREPEAT121(macro, data)     MREPEAT120(macro, data)   macro(120, data)
#define MREPEAT122(macro, data)     MREPEAT121(macro, data)   macro(121, data)
#define MREPEAT123(macro, data)     MREPEAT122(macro, data)   macro(122, data)
#define MREPEAT124(macro, data)     MREPEAT123(macro, data)   macro(123, data)
#define MREPEAT125(macro, data)     MREPEAT124(macro, data)   macro(124, data)
#define MREPEAT126(macro, data)     MREPEAT125(macro, data)   macro(125, data)
#define MREPEAT127(macro, data)     MREPEAT126(macro, data)   macro(126, data)
#define MREPEAT128(macro, data)     MREPEAT127(macro, data)   macro(127, data)
#define MREPEAT129(macro, data)     MREPEAT128(macro, data)   macro(128, data)
#define MREPEAT130(macro, data)     MREPEAT129(macro, data)   macro(129, data)
#define MREPEAT131(macro, data)     MREPEAT130(macro, data)   macro(130, data)
#define MREPEAT132(macro, data)     MREPEAT131(macro, data)   macro(131, data)
#define MREPEAT133(macro, data)     MREPEAT132(macro, data)   macro(132, data)
#define MREPEAT134(macro, data)     MREPEAT133(macro, data)   macro(133, data)
#define MREPEAT135(macro, data)     MREPEAT134(macro, data)   macro(134, data)
#define MREPEAT136(macro, data)     MREPEAT135(macro, data)   macro(135, data)
#define MREPEAT137(macro, data)     MREPEAT136(macro, data)   macro(136, data)
#define MREPEAT138(macro, data)     MREPEAT137(macro, data)   macro(137, data)
#define MREPEAT139(macro, data)     MREPEAT138(macro, data)   macro(138, data)
#define MREPEAT140(macro, data)     MREPEAT139(macro, data)   macro(139, data)
#define MREPEAT141(macro, data)     MREPEAT140(macro, data)   macro(140, data)
#define MREPEAT142(macro, data)     MREPEAT141(macro, data)   macro(141, data)
#define MREPEAT143(macro, data)     MREPEAT142(macro, data)   macro(142, data)
#define MREPEAT144(macro, data)     MREPEAT143(macro, data)   macro(143, data)
#define MREPEAT145(macro, data)     MREPEAT144(macro, data)   macro(144, data)
#define MREPEAT146(macro, data)     MREPEAT145(macro, data)   macro(145, data)
#define MREPEAT147(macro, data)     MREPEAT146(macro, data)   macro(146, data)
#define MREPEAT148(macro, data)     MREPEAT147(macro, data)   macro(147, data)
#define MREPEAT149(macro, data)     MREPEAT148(macro, data)   macro(148, data)
#define MREPEAT150(macro, data)     MREPEAT149(macro, data)   macro(149, data)
#define MREPEAT151(macro, data)     MREPEAT150(macro, data)   macro(150, data)
#define MREPEAT152(macro, data)     MREPEAT151(macro, data)   macro(151, data)
#define MREPEAT153(macro, data)     MREPEAT152(macro, data)   macro(152, data)
#define MREPEAT154(macro, data)     MREPEAT153(macro, data)   macro(153, data)
#define MREPEAT155(macro, data)     MREPEAT154(macro, data)   macro(154, data)
#define MREPEAT156(macro, data)     MREPEAT155(macro, data)   macro(155, data)
#define MREPEAT157(macro, data)     MREPEAT156(macro, data)   macro(156, data)
#define MREPEAT158(macro, data)     MREPEAT157(macro, data)   macro(157, data)
#define MREPEAT159(macro, data)     MREPEAT158(macro, data)   macro(158, data)
#define MREPEAT160(macro, data)     MREPEAT159(macro, data)   macro(159, data)
#define MREPEAT161(macro, data)     MREPEAT160(macro, data)   macro(160, data)
#define MREPEAT162(macro, data)     MREPEAT161(macro, data)   macro(161, data)
#define MREPEAT163(macro, data)     MREPEAT162(macro, data)   macro(162, data)
#define MREPEAT164(macro, data)     MREPEAT163(macro, data)   macro(163, data)
#define MREPEAT165(macro, data)     MREPEAT164(macro, data)   macro(164, data)
#define MREPEAT166(macro, data)     MREPEAT165(macro, data)   macro(165, data)
#define MREPEAT167(macro, data)     MREPEAT166(macro, data)   macro(166, data)
#define MREPEAT168(macro, data)     MREPEAT167(macro, data)   macro(167, data)
#define MREPEAT169(macro, data)     MREPEAT168(macro, data)   macro(168, data)
#define MREPEAT170(macro, data)     MREPEAT169(macro, data)   macro(169, data)
#define MREPEAT171(macro, data)     MREPEAT170(macro, data)   macro(170, data)
#define MREPEAT172(macro, data)     MREPEAT171(macro, data)   macro(171, data)
#define MREPEAT173(macro, data)     MREPEAT172(macro, data)   macro(172, data)
#define MREPEAT174(macro, data)     MREPEAT173(macro, data)   macro(173, data)
#define MREPEAT175(macro, data)     MREPEAT174(macro, data)   macro(174, data)
#define MREPEAT176(macro, data)     MREPEAT175(macro, data)   macro(175, data)
#define MREPEAT177(macro, data)     MREPEAT176(macro, data)   macro(176, data)
#define MREPEAT178(macro, data)     MREPEAT177(macro, data)   macro(177, data)
#define MREPEAT179(macro, data)     MREPEAT178(macro, data)   macro(178, data)
#define MREPEAT180(macro, data)     MREPEAT179(macro, data)   macro(179, data)
#define MREPEAT181(macro, data)     MREPEAT180(macro, data)   macro(180, data)
#define MREPEAT182(macro, data)     MREPEAT181(macro, data)   macro(181, data)
#define MREPEAT183(macro, data)     MREPEAT182(macro, data)   macro(182, data)
#define MREPEAT184(macro, data)     MREPEAT183(macro, data)   macro(183, data)
#define MREPEAT185(macro, data)     MREPEAT184(macro, data)   macro(184, data)
#define MREPEAT186(macro, data)     MREPEAT185(macro, data)   macro(185, data)
#define MREPEAT187(macro, data)     MREPEAT186(macro, data)   macro(186, data)
#define MREPEAT188(macro, data)     MREPEAT187(macro, data)   macro(187, data)
#define MREPEAT189(macro, data)     MREPEAT188(macro, data)   macro(188, data)
#define MREPEAT190(macro, data)     MREPEAT189(macro, data)   macro(189, data)
#define MREPEAT191(macro, data)     MREPEAT190(macro, data)   macro(190, data)
#define MREPEAT192(macro, data)     MREPEAT191(macro, data)   macro(191, data)
#define MREPEAT193(macro, data)     MREPEAT192(macro, data)   macro(192, data)
#define MREPEAT194(macro, data)     MREPEAT193(macro, data)   macro(193, data)
#define MREPEAT195(macro, data)     MREPEAT194(macro, data)   macro(194, data)
#define MREPEAT196(macro, data)     MREPEAT195(macro, data)   macro(195, data)
#define MREPEAT197(macro, data)     MREPEAT196(macro, data)   macro(196, data)
#define MREPEAT198(macro, data)     MREPEAT197(macro, data)   macro(197, data)
#define MREPEAT199(macro, data)     MREPEAT198(macro, data)   macro(198, data)
#define MREPEAT200(macro, data)     MREPEAT199(macro, data)   macro(199, data)
#define MREPEAT201(macro, data)     MREPEAT200(macro, data)   macro(200, data)
#define MREPEAT202(macro, data)     MREPEAT201(macro, data)   macro(201, data)
#define MREPEAT203(macro, data)     MREPEAT202(macro, data)   macro(202, data)
#define MREPEAT204(macro, data)     MREPEAT203(macro, data)   macro(203, data)
#define MREPEAT205(macro, data)     MREPEAT204(macro, data)   macro(204, data)
#define MREPEAT206(macro, data)     MREPEAT205(macro, data)   macro(205, data)
#define MREPEAT207(macro, data)     MREPEAT206(macro, data)   macro(206, data)
#define MREPEAT208(macro, data)     MREPEAT207(macro, data)   macro(207, data)
#define MREPEAT209(macro, data)     MREPEAT208(macro, data)   macro(208, data)
#define MREPEAT210(macro, data)     MREPEAT209(macro, data)   macro(209, data)
#define MREPEAT211(macro, data)     MREPEAT210(macro, data)   macro(210, data)
#define MREPEAT212(macro, data)     MREPEAT211(macro, data)   macro(211, data)
#define MREPEAT213(macro, data)     MREPEAT212(macro, data)   macro(212, data)
#define MREPEAT214(macro, data)     MREPEAT213(macro, data)   macro(213, data)
#define MREPEAT215(macro, data)     MREPEAT214(macro, data)   macro(214, data)
#define MREPEAT216(macro, data)     MREPEAT215(macro, data)   macro(215, data)
#define MREPEAT217(macro, data)     MREPEAT216(macro, data)   macro(216, data)
#define MREPEAT218(macro, data)     MREPEAT217(macro, data)   macro(217, data)
#define MREPEAT219(macro, data)     MREPEAT218(macro, data)   macro(218, data)
#define MREPEAT220(macro, data)     MREPEAT219(macro, data)   macro(219, data)
#define MREPEAT221(macro, data)     MREPEAT220(macro, data)   macro(220, data)
#define MREPEAT222(macro, data)     MREPEAT221(macro, data)   macro(221, data)
#define MREPEAT223(macro, data)     MREPEAT222(macro, data)   macro(222, data)
#define MREPEAT224(macro, data)     MREPEAT223(macro, data)   macro(223, data)
#define MREPEAT225(macro, data)     MREPEAT224(macro, data)   macro(224, data)
#define MREPEAT226(macro, data)     MREPEAT225(macro, data)   macro(225, data)
#define MREPEAT227(macro, data)     MREPEAT226(macro, data)   macro(226, data)
#define MREPEAT228(macro, data)     MREPEAT227(macro, data)   macro(227, data)
#define MREPEAT229(macro, data)     MREPEAT228(macro, data)   macro(228, data)
#define MREPEAT230(macro, data)     MREPEAT229(macro, data)   macro(229, data)
#define MREPEAT231(macro, data)     MREPEAT230(macro, data)   macro(230, data)
#define MREPEAT232(macro, data)     MREPEAT231(macro, data)   macro(231, data)
#define MREPEAT233(macro, data)     MREPEAT232(macro, data)   macro(232, data)
#define MREPEAT234(macro, data)     MREPEAT233(macro, data)   macro(233, data)
#define MREPEAT235(macro, data)     MREPEAT234(macro, data)   macro(234, data)
#define MREPEAT236(macro, data)     MREPEAT235(macro, data)   macro(235, data)
#define MREPEAT237(macro, data)     MREPEAT236(macro, data)   macro(236, data)
#define MREPEAT238(macro, data)     MREPEAT237(macro, data)   macro(237, data)
#define MREPEAT239(macro, data)     MREPEAT238(macro, data)   macro(238, data)
#define MREPEAT240(macro, data)     MREPEAT239(macro, data)   macro(239, data)
#define MREPEAT241(macro, data)     MREPEAT240(macro, data)   macro(240, data)
#define MREPEAT242(macro, data)     MREPEAT241(macro, data)   macro(241, data)
#define MREPEAT243(macro, data)     MREPEAT242(macro, data)   macro(242, data)
#define MREPEAT244(macro, data)     MREPEAT243(macro, data)   macro(243, data)
#define MREPEAT245(macro, data)     MREPEAT244(macro, data)   macro(244, data)
#define MREPEAT246(macro, data)     MREPEAT245(macro, data)   macro(245, data)
#define MREPEAT247(macro, data)     MREPEAT246(macro, data)   macro(246, data)
#define MREPEAT248(macro, data)     MREPEAT247(macro, data)   macro(247, data)
#define MREPEAT249(macro, data)     MREPEAT248(macro, data)   macro(248, data)
#define MREPEAT250(macro, data)     MREPEAT249(macro, data)   macro(249, data)
#define MREPEAT251(macro, data)     MREPEAT250(macro, data)   macro(250, data)
#define MREPEAT252(macro, data)     MREPEAT251(macro, data)   macro(251, data)
#define MREPEAT253(macro, data)     MREPEAT252(macro, data)   macro(252, data)
#define MREPEAT254(macro, data)     MREPEAT253(macro, data)   macro(253, data)
#define MREPEAT255(macro, data)     MREPEAT254(macro, data)   macro(254, data)
#define MREPEAT256(macro, data)     MREPEAT255(macro, data)   macro(255, data)
#define MREPEAT257(macro, data)     MREPEAT256(macro, data)   macro(256, data)
#define MREPEAT258(macro, data)     MREPEAT257(macro, data)   macro(257, data)
#define MREPEAT259(macro, data)     MREPEAT258(macro, data)   macro(258, data)
#define MREPEAT260(macro, data)     MREPEAT259(macro, data)   macro(259, data)
#define MREPEAT261(macro, data)     MREPEAT260(macro, data)   macro(260, data)
#define MREPEAT262(macro, data)     MREPEAT261(macro, data)   macro(261, data)
#define MREPEAT263(macro, data)     MREPEAT262(macro, data)   macro(262, data)
#define MREPEAT264(macro, data)     MREPEAT263(macro, data)   macro(263, data)
#define MREPEAT265(macro, data)     MREPEAT264(macro, data)   macro(264, data)
#define MREPEAT266(macro, data)     MREPEAT265(macro, data)   macro(265, data)
#define MREPEAT267(macro, data)     MREPEAT266(macro, data)   macro(266, data)
#define MREPEAT268(macro, data)     MREPEAT267(macro, data)   macro(267, data)
#define MREPEAT269(macro, data)     MREPEAT268(macro, data)   macro(268, data)
#define MREPEAT270(macro, data)     MREPEAT269(macro, data)   macro(269, data)
#define MREPEAT271(macro, data)     MREPEAT270(macro, data)   macro(270, data)
#define MREPEAT272(macro, data)     MREPEAT271(macro, data)   macro(271, data)
#define MREPEAT273(macro, data)     MREPEAT272(macro, data)   macro(272, data)
#define MREPEAT274(macro, data)     MREPEAT273(macro, data)   macro(273, data)
#define MREPEAT275(macro, data)     MREPEAT274(macro, data)   macro(274, data)
#define MREPEAT276(macro, data)     MREPEAT275(macro, data)   macro(275, data)
#define MREPEAT277(macro, data)     MREPEAT276(macro, data)   macro(276, data)
#define MREPEAT278(macro, data)     MREPEAT277(macro, data)   macro(277, data)
#define MREPEAT279(macro, data)     MREPEAT278(macro, data)   macro(278, data)
#define MREPEAT280(macro, data)     MREPEAT279(macro, data)   macro(279, data)
#define MREPEAT281(macro, data)     MREPEAT280(macro, data)   macro(280, data)
#define MREPEAT282(macro, data)     MREPEAT281(macro, data)   macro(281, data)
#define MREPEAT283(macro, data)     MREPEAT282(macro, data)   macro(282, data)
#define MREPEAT284(macro, data)     MREPEAT283(macro, data)   macro(283, data)
#define MREPEAT285(macro, data)     MREPEAT284(macro, data)   macro(284, data)
#define MREPEAT286(macro, data)     MREPEAT285(macro, data)   macro(285, data)
#define MREPEAT287(macro, data)     MREPEAT286(macro, data)   macro(286, data)
#define MREPEAT288(macro, data)     MREPEAT287(macro, data)   macro(287, data)
#define MREPEAT289(macro, data)     MREPEAT288(macro, data)   macro(288, data)
#define MREPEAT290(macro, data)     MREPEAT289(macro, data)   macro(289, data)
#define MREPEAT291(macro, data)     MREPEAT290(macro, data)   macro(290, data)
#define MREPEAT292(macro, data)     MREPEAT291(macro, data)   macro(291, data)
#define MREPEAT293(macro, data)     MREPEAT292(macro, data)   macro(292, data)
#define MREPEAT294(macro, data)     MREPEAT293(macro, data)   macro(293, data)
#define MREPEAT295(macro, data)     MREPEAT294(macro, data)   macro(294, data)
#define MREPEAT296(macro, data)     MREPEAT295(macro, data)   macro(295, data)
#define MREPEAT297(macro, data)     MREPEAT296(macro, data)   macro(296, data)
#define MREPEAT298(macro, data)     MREPEAT297(macro, data)   macro(297, data)
#define MREPEAT299(macro, data)     MREPEAT298(macro, data)   macro(298, data)
#define MREPEAT300(macro, data)     MREPEAT299(macro, data)   macro(299, data)
#define MREPEAT301(macro, data)     MREPEAT300(macro, data)   macro(300, data)
#define MREPEAT302(macro, data)     MREPEAT301(macro, data)   macro(301, data)
#define MREPEAT303(macro, data)     MREPEAT302(macro, data)   macro(302, data)
#define MREPEAT304(macro, data)     MREPEAT303(macro, data)   macro(303, data)
#define MREPEAT305(macro, data)     MREPEAT304(macro, data)   macro(304, data)
#define MREPEAT306(macro, data)     MREPEAT305(macro, data)   macro(305, data)
#define MREPEAT307(macro, data)     MREPEAT306(macro, data)   macro(306, data)
#define MREPEAT308(macro, data)     MREPEAT307(macro, data)   macro(307, data)
#define MREPEAT309(macro, data)     MREPEAT308(macro, data)   macro(308, data)
#define MREPEAT310(macro, data)     MREPEAT309(macro, data)   macro(309, data)
#define MREPEAT311(macro, data)     MREPEAT310(macro, data)   macro(310, data)
#define MREPEAT312(macro, data)     MREPEAT311(macro, data)   macro(311, data)
#define MREPEAT313(macro, data)     MREPEAT312(macro, data)   macro(312, data)
#define MREPEAT314(macro, data)     MREPEAT313(macro, data)   macro(313, data)
#define MREPEAT315(macro, data)     MREPEAT314(macro, data)   macro(314, data)
#define MREPEAT316(macro, data)     MREPEAT315(macro, data)   macro(315, data)
#define MREPEAT317(macro, data)     MREPEAT316(macro, data)   macro(316, data)
#define MREPEAT318(macro, data)     MREPEAT317(macro, data)   macro(317, data)
#define MREPEAT319(macro, data)     MREPEAT318(macro, data)   macro(318, data)
#define MREPEAT320(macro, data)     MREPEAT319(macro, data)   macro(319, data)
#define MREPEAT321(macro, data)     MREPEAT320(macro, data)   macro(320, data)
#define MREPEAT322(macro, data)     MREPEAT321(macro, data)   macro(321, data)
#define MREPEAT323(macro, data)     MREPEAT322(macro, data)   macro(322, data)
#define MREPEAT324(macro, data)     MREPEAT323(macro, data)   macro(323, data)
#define MREPEAT325(macro, data)     MREPEAT324(macro, data)   macro(324, data)
#define MREPEAT326(macro, data)     MREPEAT325(macro, data)   macro(325, data)
#define MREPEAT327(macro, data)     MREPEAT326(macro, data)   macro(326, data)
#define MREPEAT328(macro, data)     MREPEAT327(macro, data)   macro(327, data)
#define MREPEAT329(macro, data)     MREPEAT328(macro, data)   macro(328, data)
#define MREPEAT330(macro, data)     MREPEAT329(macro, data)   macro(329, data)
#define MREPEAT331(macro, data)     MREPEAT330(macro, data)   macro(330, data)
#define MREPEAT332(macro, data)     MREPEAT331(macro, data)   macro(331, data)
#define MREPEAT333(macro, data)     MREPEAT332(macro, data)   macro(332, data)
#define MREPEAT334(macro, data)     MREPEAT333(macro, data)   macro(333, data)
#define MREPEAT335(macro, data)     MREPEAT334(macro, data)   macro(334, data)
#define MREPEAT336(macro, data)     MREPEAT335(macro, data)   macro(335, data)
#define MREPEAT337(macro, data)     MREPEAT336(macro, data)   macro(336, data)
#define MREPEAT338(macro, data)     MREPEAT337(macro, data)   macro(337, data)
#define MREPEAT339(macro, data)     MREPEAT338(macro, data)   macro(338, data)
#define MREPEAT340(macro, data)     MREPEAT339(macro, data)   macro(339, data)
#define MREPEAT341(macro, data)     MREPEAT340(macro, data)   macro(340, data)
#define MREPEAT342(macro, data)     MREPEAT341(macro, data)   macro(341, data)
#define MREPEAT343(macro, data)     MREPEAT342(macro, data)   macro(342, data)
#define MREPEAT344(macro, data)     MREPEAT343(macro, data)   macro(343, data)
#define MREPEAT345(macro, data)     MREPEAT344(macro, data)   macro(344, data)
#define MREPEAT346(macro, data)     MREPEAT345(macro, data)   macro(345, data)
#define MREPEAT347(macro, data)     MREPEAT346(macro, data)   macro(346, data)
#define MREPEAT348(macro, data)     MREPEAT347(macro, data)   macro(347, data)
#define MREPEAT349(macro, data)     MREPEAT348(macro, data)   macro(348, data)
#define MREPEAT350(macro, data)     MREPEAT349(macro, data)   macro(349, data)
#define MREPEAT351(macro, data)     MREPEAT350(macro, data)   macro(350, data)
#define MREPEAT352(macro, data)     MREPEAT351(macro, data)   macro(351, data)
#define MREPEAT353(macro, data)     MREPEAT352(macro, data)   macro(352, data)
#define MREPEAT354(macro, data)     MREPEAT353(macro, data)   macro(353, data)
#define MREPEAT355(macro, data)     MREPEAT354(macro, data)   macro(354, data)
#define MREPEAT356(macro, data)     MREPEAT355(macro, data)   macro(355, data)
#define MREPEAT357(macro, data)     MREPEAT356(macro, data)   macro(356, data)
#define MREPEAT358(macro, data)     MREPEAT357(macro, data)   macro(357, data)
#define MREPEAT359(macro, data)     MREPEAT358(macro, data)   macro(358, data)
#define MREPEAT360(macro, data)     MREPEAT359(macro, data)   macro(359, data)
#define MREPEAT361(macro, data)     MREPEAT360(macro, data)   macro(360, data)
#define MREPEAT362(macro, data)     MREPEAT361(macro, data)   macro(361, data)
#define MREPEAT363(macro, data)     MREPEAT362(macro, data)   macro(362, data)
#define MREPEAT364(macro, data)     MREPEAT363(macro, data)   macro(363, data)
#define MREPEAT365(macro, data)     MREPEAT364(macro, data)   macro(364, data)
#define MREPEAT366(macro, data)     MREPEAT365(macro, data)   macro(365, data)
#define MREPEAT367(macro, data)     MREPEAT366(macro, data)   macro(366, data)
#define MREPEAT368(macro, data)     MREPEAT367(macro, data)   macro(367, data)
#define MREPEAT369(macro, data)     MREPEAT368(macro, data)   macro(368, data)
#define MREPEAT370(macro, data)     MREPEAT369(macro, data)   macro(369, data)
#define MREPEAT371(macro, data)     MREPEAT370(macro, data)   macro(370, data)
#define MREPEAT372(macro, data)     MREPEAT371(macro, data)   macro(371, data)
#define MREPEAT373(macro, data)     MREPEAT372(macro, data)   macro(372, data)
#define MREPEAT374(macro, data)     MREPEAT373(macro, data)   macro(373, data)
#define MREPEAT375(macro, data)     MREPEAT374(macro, data)   macro(374, data)
#define MREPEAT376(macro, data)     MREPEAT375(macro, data)   macro(375, data)
#define MREPEAT377(macro, data)     MREPEAT376(macro, data)   macro(376, data)
#define MREPEAT378(macro, data)     MREPEAT377(macro, data)   macro(377, data)
#define MREPEAT379(macro, data)     MREPEAT378(macro, data)   macro(378, data)
#define MREPEAT380(macro, data)     MREPEAT379(macro, data)   macro(379, data)
#define MREPEAT381(macro, data)     MREPEAT380(macro, data)   macro(380, data)
#define MREPEAT382(macro, data)     MREPEAT381(macro, data)   macro(381, data)
#define MREPEAT383(macro, data)     MREPEAT382(macro, data)   macro(382, data)
#define MREPEAT384(macro, data)     MREPEAT383(macro, data)   macro(383, data)
#define MREPEAT385(macro, data)     MREPEAT384(macro, data)   macro(384, data)
#define MREPEAT386(macro, data)     MREPEAT385(macro, data)   macro(385, data)
#define MREPEAT387(macro, data)     MREPEAT386(macro, data)   macro(386, data)
#define MREPEAT388(macro, data)     MREPEAT387(macro, data)   macro(387, data)
#define MREPEAT389(macro, data)     MREPEAT388(macro, data)   macro(388, data)
#define MREPEAT390(macro, data)     MREPEAT389(macro, data)   macro(389, data)
#define MREPEAT391(macro, data)     MREPEAT390(macro, data)   macro(390, data)
#define MREPEAT392(macro, data)     MREPEAT391(macro, data)   macro(391, data)
#define MREPEAT393(macro, data)     MREPEAT392(macro, data)   macro(392, data)
#define MREPEAT394(macro, data)     MREPEAT393(macro, data)   macro(393, data)
#define MREPEAT395(macro, data)     MREPEAT394(macro, data)   macro(394, data)
#define MREPEAT396(macro, data)     MREPEAT395(macro, data)   macro(395, data)
#define MREPEAT397(macro, data)     MREPEAT396(macro, data)   macro(396, data)
#define MREPEAT398(macro, data)     MREPEAT397(macro, data)   macro(397, data)
#define MREPEAT399(macro, data)     MREPEAT398(macro, data)   macro(398, data)
#define MREPEAT400(macro, data)     MREPEAT399(macro, data)   macro(399, data)
#define MREPEAT401(macro, data)     MREPEAT400(macro, data)   macro(400, data)
#define MREPEAT402(macro, data)     MREPEAT401(macro, data)   macro(401, data)
#define MREPEAT403(macro, data)     MREPEAT402(macro, data)   macro(402, data)
#define MREPEAT404(macro, data)     MREPEAT403(macro, data)   macro(403, data)
#define MREPEAT405(macro, data)     MREPEAT404(macro, data)   macro(404, data)
#define MREPEAT406(macro, data)     MREPEAT405(macro, data)   macro(405, data)
#define MREPEAT407(macro, data)     MREPEAT406(macro, data)   macro(406, data)
#define MREPEAT408(macro, data)     MREPEAT407(macro, data)   macro(407, data)
#define MREPEAT409(macro, data)     MREPEAT408(macro, data)   macro(408, data)
#define MREPEAT410(macro, data)     MREPEAT409(macro, data)   macro(409, data)
#define MREPEAT411(macro, data)     MREPEAT410(macro, data)   macro(410, data)
#define MREPEAT412(macro, data)     MREPEAT411(macro, data)   macro(411, data)
#define MREPEAT413(macro, data)     MREPEAT412(macro, data)   macro(412, data)
#define MREPEAT414(macro, data)     MREPEAT413(macro, data)   macro(413, data)
#define MREPEAT415(macro, data)     MREPEAT414(macro, data)   macro(414, data)
#define MREPEAT416(macro, data)     MREPEAT415(macro, data)   macro(415, data)
#define MREPEAT417(macro, data)     MREPEAT416(macro, data)   macro(416, data)
#define MREPEAT418(macro, data)     MREPEAT417(macro, data)   macro(417, data)
#define MREPEAT419(macro, data)     MREPEAT418(macro, data)   macro(418, data)
#define MREPEAT420(macro, data)     MREPEAT419(macro, data)   macro(419, data)
#define MREPEAT421(macro, data)     MREPEAT420(macro, data)   macro(420, data)
#define MREPEAT422(macro, data)     MREPEAT421(macro, data)   macro(421, data)
#define MREPEAT423(macro, data)     MREPEAT422(macro, data)   macro(422, data)
#define MREPEAT424(macro, data)     MREPEAT423(macro, data)   macro(423, data)
#define MREPEAT425(macro, data)     MREPEAT424(macro, data)   macro(424, data)
#define MREPEAT426(macro, data)     MREPEAT425(macro, data)   macro(425, data)
#define MREPEAT427(macro, data)     MREPEAT426(macro, data)   macro(426, data)
#define MREPEAT428(macro, data)     MREPEAT427(macro, data)   macro(427, data)
#define MREPEAT429(macro, data)     MREPEAT428(macro, data)   macro(428, data)
#define MREPEAT430(macro, data)     MREPEAT429(macro, data)   macro(429, data)
#define MREPEAT431(macro, data)     MREPEAT430(macro, data)   macro(430, data)
#define MREPEAT432(macro, data)     MREPEAT431(macro, data)   macro(431, data)
#define MREPEAT433(macro, data)     MREPEAT432(macro, data)   macro(432, data)
#define MREPEAT434(macro, data)     MREPEAT433(macro, data)   macro(433, data)
#define MREPEAT435(macro, data)     MREPEAT434(macro, data)   macro(434, data)
#define MREPEAT436(macro, data)     MREPEAT435(macro, data)   macro(435, data)
#define MREPEAT437(macro, data)     MREPEAT436(macro, data)   macro(436, data)
#define MREPEAT438(macro, data)     MREPEAT437(macro, data)   macro(437, data)
#define MREPEAT439(macro, data)     MREPEAT438(macro, data)   macro(438, data)
#define MREPEAT440(macro, data)     MREPEAT439(macro, data)   macro(439, data)
#define MREPEAT441(macro, data)     MREPEAT440(macro, data)   macro(440, data)
#define MREPEAT442(macro, data)     MREPEAT441(macro, data)   macro(441, data)
#define MREPEAT443(macro, data)     MREPEAT442(macro, data)   macro(442, data)
#define MREPEAT444(macro, data)     MREPEAT443(macro, data)   macro(443, data)
#define MREPEAT445(macro, data)     MREPEAT444(macro, data)   macro(444, data)
#define MREPEAT446(macro, data)     MREPEAT445(macro, data)   macro(445, data)
#define MREPEAT447(macro, data)     MREPEAT446(macro, data)   macro(446, data)
#define MREPEAT448(macro, data)     MREPEAT447(macro, data)   macro(447, data)
#define MREPEAT449(macro, data)     MREPEAT448(macro, data)   macro(448, data)
#define MREPEAT450(macro, data)     MREPEAT449(macro, data)   macro(449, data)
#define MREPEAT451(macro, data)     MREPEAT450(macro, data)   macro(450, data)
#define MREPEAT452(macro, data)     MREPEAT451(macro, data)   macro(451, data)
#define MREPEAT453(macro, data)     MREPEAT452(macro, data)   macro(452, data)
#define MREPEAT454(macro, data)     MREPEAT453(macro, data)   macro(453, data)
#define MREPEAT455(macro, data)     MREPEAT454(macro, data)   macro(454, data)
#define MREPEAT456(macro, data)     MREPEAT455(macro, data)   macro(455, data)
#define MREPEAT457(macro, data)     MREPEAT456(macro, data)   macro(456, data)
#define MREPEAT458(macro, data)     MREPEAT457(macro, data)   macro(457, data)
#define MREPEAT459(macro, data)     MREPEAT458(macro, data)   macro(458, data)
#define MREPEAT460(macro, data)     MREPEAT459(macro, data)   macro(459, data)
#define MREPEAT461(macro, data)     MREPEAT460(macro, data)   macro(460, data)
#define MREPEAT462(macro, data)     MREPEAT461(macro, data)   macro(461, data)
#define MREPEAT463(macro, data)     MREPEAT462(macro, data)   macro(462, data)
#define MREPEAT464(macro, data)     MREPEAT463(macro, data)   macro(463, data)
#define MREPEAT465(macro, data)     MREPEAT464(macro, data)   macro(464, data)
#define MREPEAT466(macro, data)     MREPEAT465(macro, data)   macro(465, data)
#define MREPEAT467(macro, data)     MREPEAT466(macro, data)   macro(466, data)
#define MREPEAT468(macro, data)     MREPEAT467(macro, data)   macro(467, data)
#define MREPEAT469(macro, data)     MREPEAT468(macro, data)   macro(468, data)
#define MREPEAT470(macro, data)     MREPEAT469(macro, data)   macro(469, data)
#define MREPEAT471(macro, data)     MREPEAT470(macro, data)   macro(470, data)
#define MREPEAT472(macro, data)     MREPEAT471(macro, data)   macro(471, data)
#define MREPEAT473(macro, data)     MREPEAT472(macro, data)   macro(472, data)
#define MREPEAT474(macro, data)     MREPEAT473(macro, data)   macro(473, data)
#define MREPEAT475(macro, data)     MREPEAT474(macro, data)   macro(474, data)
#define MREPEAT476(macro, data)     MREPEAT475(macro, data)   macro(475, data)
#define MREPEAT477(macro, data)     MREPEAT476(macro, data)   macro(476, data)
#define MREPEAT478(macro, data)     MREPEAT477(macro, data)   macro(477, data)
#define MREPEAT479(macro, data)     MREPEAT478(macro, data)   macro(478, data)
#define MREPEAT480(macro, data)     MREPEAT479(macro, data)   macro(479, data)
#define MREPEAT481(macro, data)     MREPEAT480(macro, data)   macro(480, data)
#define MREPEAT482(macro, data)     MREPEAT481(macro, data)   macro(481, data)
#define MREPEAT483(macro, data)     MREPEAT482(macro, data)   macro(482, data)
#define MREPEAT484(macro, data)     MREPEAT483(macro, data)   macro(483, data)
#define MREPEAT485(macro, data)     MREPEAT484(macro, data)   macro(484, data)
#define MREPEAT486(macro, data)     MREPEAT485(macro, data)   macro(485, data)
#define MREPEAT487(macro, data)     MREPEAT486(macro, data)   macro(486, data)
#define MREPEAT488(macro, data)     MREPEAT487(macro, data)   macro(487, data)
#define MREPEAT489(macro, data)     MREPEAT488(macro, data)   macro(488, data)
#define MREPEAT490(macro, data)     MREPEAT489(macro, data)   macro(489, data)
#define MREPEAT491(macro, data)     MREPEAT490(macro, data)   macro(490, data)
#define MREPEAT492(macro, data)     MREPEAT491(macro, data)   macro(491, data)
#define MREPEAT493(macro, data)     MREPEAT492(macro, data)   macro(492, data)
#define MREPEAT494(macro, data)     MREPEAT493(macro, data)   macro(493, data)
#define MREPEAT495(macro, data)     MREPEAT494(macro, data)   macro(494, data)
#define MREPEAT496(macro, data)     MREPEAT495(macro, data)   macro(495, data)
#define MREPEAT497(macro, data)     MREPEAT496(macro, data)   macro(496, data)
#define MREPEAT498(macro, data)     MREPEAT497(macro, data)   macro(497, data)
#define MREPEAT499(macro, data)     MREPEAT498(macro, data)   macro(498, data)
#define MREPEAT500(macro, data)     MREPEAT499(macro, data)   macro(499, data)
#define MREPEAT501(macro, data)     MREPEAT500(macro, data)   macro(500, data)
#define MREPEAT502(macro, data)     MREPEAT501(macro, data)   macro(501, data)
#define MREPEAT503(macro, data)     MREPEAT502(macro, data)   macro(502, data)
#define MREPEAT504(macro, data)     MREPEAT503(macro, data)   macro(503, data)
#define MREPEAT505(macro, data)     MREPEAT504(macro, data)   macro(504, data)
#define MREPEAT506(macro, data)     MREPEAT505(macro, data)   macro(505, data)
#define MREPEAT507(macro, data)     MREPEAT506(macro, data)   macro(506, data)
#define MREPEAT508(macro, data)     MREPEAT507(macro, data)   macro(507, data)
#define MREPEAT509(macro, data)     MREPEAT508(macro, data)   macro(508, data)
#define MREPEAT510(macro, data)     MREPEAT509(macro, data)   macro(509, data)
#define MREPEAT511(macro, data)     MREPEAT510(macro, data)   macro(510, data)
#define MREPEAT512(macro, data)     MREPEAT511(macro, data)   macro(511, data)

#define MREPEAT_ODD(count, macro, data)       TPASTE2(MREPEAT_ODD, count)(macro, data)

#define MREPEAT_ODD0(  macro, data)
#define MREPEAT_ODD1(  macro, data)     MREPEAT_ODD0(  macro, data)   macro(  1, data)
#define MREPEAT_ODD2(  macro, data)     MREPEAT_ODD1(  macro, data)   macro(  3, data)
#define MREPEAT_ODD3(  macro, data)     MREPEAT_ODD2(  macro, data)   macro(  5, data)
#define MREPEAT_ODD4(  macro, data)     MREPEAT_ODD3(  macro, data)   macro(  7, data)
#define MREPEAT_ODD5(  macro, data)     MREPEAT_ODD4(  macro, data)   macro(  9, data)
#define MREPEAT_ODD6(  macro, data)     MREPEAT_ODD5(  macro, data)   macro(  11, data)
#define MREPEAT_ODD7(  macro, data)     MREPEAT_ODD6(  macro, data)   macro(  13, data)
#define MREPEAT_ODD8(  macro, data)     MREPEAT_ODD7(  macro, data)   macro(  15, data)
#define MREPEAT_ODD9(  macro, data)     MREPEAT_ODD8(  macro, data)   macro(  17, data)
#define MREPEAT_ODD10( macro, data)     MREPEAT_ODD9(  macro, data)   macro(  19, data)
#define MREPEAT_ODD11( macro, data)     MREPEAT_ODD10( macro, data)   macro( 21, data)
#define MREPEAT_ODD12( macro, data)     MREPEAT_ODD11( macro, data)   macro( 23, data)
#define MREPEAT_ODD13( macro, data)     MREPEAT_ODD12( macro, data)   macro( 25, data)
#define MREPEAT_ODD14( macro, data)     MREPEAT_ODD13( macro, data)   macro( 27, data)
#define MREPEAT_ODD15( macro, data)     MREPEAT_ODD14( macro, data)   macro( 29, data)
#define MREPEAT_ODD16( macro, data)     MREPEAT_ODD15( macro, data)   macro( 31, data)
#define MREPEAT_ODD17( macro, data)     MREPEAT_ODD16( macro, data)   macro( 33, data)
#define MREPEAT_ODD18( macro, data)     MREPEAT_ODD17( macro, data)   macro( 35, data)
#define MREPEAT_ODD19( macro, data)     MREPEAT_ODD18( macro, data)   macro( 37, data)
#define MREPEAT_ODD20( macro, data)     MREPEAT_ODD19( macro, data)   macro( 39, data)
#define MREPEAT_ODD21( macro, data)     MREPEAT_ODD20( macro, data)   macro( 41, data)
#define MREPEAT_ODD22( macro, data)     MREPEAT_ODD21( macro, data)   macro( 43, data)
#define MREPEAT_ODD23( macro, data)     MREPEAT_ODD22( macro, data)   macro( 45, data)
#define MREPEAT_ODD24( macro, data)     MREPEAT_ODD23( macro, data)   macro( 47, data)
#define MREPEAT_ODD25( macro, data)     MREPEAT_ODD24( macro, data)   macro( 49, data)
#define MREPEAT_ODD26( macro, data)     MREPEAT_ODD25( macro, data)   macro( 51, data)
#define MREPEAT_ODD27( macro, data)     MREPEAT_ODD26( macro, data)   macro( 53, data)
#define MREPEAT_ODD28( macro, data)     MREPEAT_ODD27( macro, data)   macro( 55, data)
#define MREPEAT_ODD29( macro, data)     MREPEAT_ODD28( macro, data)   macro( 57, data)
#define MREPEAT_ODD30( macro, data)     MREPEAT_ODD29( macro, data)   macro( 59, data)
#define MREPEAT_ODD31( macro, data)     MREPEAT_ODD30( macro, data)   macro( 61, data)
#define MREPEAT_ODD32( macro, data)     MREPEAT_ODD31( macro, data)   macro( 63, data)
#define MREPEAT_ODD33( macro, data)     MREPEAT_ODD32( macro, data)   macro( 65, data)
#define MREPEAT_ODD34( macro, data)     MREPEAT_ODD33( macro, data)   macro( 67, data)
#define MREPEAT_ODD35( macro, data)     MREPEAT_ODD34( macro, data)   macro( 69, data)
#define MREPEAT_ODD36( macro, data)     MREPEAT_ODD35( macro, data)   macro( 71, data)
#define MREPEAT_ODD37( macro, data)     MREPEAT_ODD36( macro, data)   macro( 73, data)
#define MREPEAT_ODD38( macro, data)     MREPEAT_ODD37( macro, data)   macro( 75, data)
#define MREPEAT_ODD39( macro, data)     MREPEAT_ODD38( macro, data)   macro( 77, data)
#define MREPEAT_ODD40( macro, data)     MREPEAT_ODD39( macro, data)   macro( 79, data)
#define MREPEAT_ODD41( macro, data)     MREPEAT_ODD40( macro, data)   macro( 81, data)
#define MREPEAT_ODD42( macro, data)     MREPEAT_ODD41( macro, data)   macro( 83, data)
#define MREPEAT_ODD43( macro, data)     MREPEAT_ODD42( macro, data)   macro( 85, data)
#define MREPEAT_ODD44( macro, data)     MREPEAT_ODD43( macro, data)   macro( 87, data)
#define MREPEAT_ODD45( macro, data)     MREPEAT_ODD44( macro, data)   macro( 89, data)
#define MREPEAT_ODD46( macro, data)     MREPEAT_ODD45( macro, data)   macro( 91, data)
#define MREPEAT_ODD47( macro, data)     MREPEAT_ODD46( macro, data)   macro( 93, data)
#define MREPEAT_ODD48( macro, data)     MREPEAT_ODD47( macro, data)   macro( 95, data)
#define MREPEAT_ODD49( macro, data)     MREPEAT_ODD48( macro, data)   macro( 97, data)
#define MREPEAT_ODD50( macro, data)     MREPEAT_ODD49( macro, data)   macro( 99, data)
#define MREPEAT_ODD51( macro, data)     MREPEAT_ODD50( macro, data)   macro( 101, data)
#define MREPEAT_ODD52( macro, data)     MREPEAT_ODD51( macro, data)   macro( 103, data)
#define MREPEAT_ODD53( macro, data)     MREPEAT_ODD52( macro, data)   macro( 105, data)
#define MREPEAT_ODD54( macro, data)     MREPEAT_ODD53( macro, data)   macro( 107, data)
#define MREPEAT_ODD55( macro, data)     MREPEAT_ODD54( macro, data)   macro( 109, data)
#define MREPEAT_ODD56( macro, data)     MREPEAT_ODD55( macro, data)   macro( 111, data)
#define MREPEAT_ODD57( macro, data)     MREPEAT_ODD56( macro, data)   macro( 113, data)
#define MREPEAT_ODD58( macro, data)     MREPEAT_ODD57( macro, data)   macro( 115, data)
#define MREPEAT_ODD59( macro, data)     MREPEAT_ODD58( macro, data)   macro( 117, data)
#define MREPEAT_ODD60( macro, data)     MREPEAT_ODD59( macro, data)   macro( 119, data)
#define MREPEAT_ODD61( macro, data)     MREPEAT_ODD60( macro, data)   macro( 121, data)
#define MREPEAT_ODD62( macro, data)     MREPEAT_ODD61( macro, data)   macro( 123, data)
#define MREPEAT_ODD63( macro, data)     MREPEAT_ODD62( macro, data)   macro( 125, data)
#define MREPEAT_ODD64( macro, data)     MREPEAT_ODD63( macro, data)   macro( 127, data)
#define MREPEAT_ODD65( macro, data)     MREPEAT_ODD64( macro, data)   macro( 129, data)
#define MREPEAT_ODD66( macro, data)     MREPEAT_ODD65( macro, data)   macro( 131, data)
#define MREPEAT_ODD67( macro, data)     MREPEAT_ODD66( macro, data)   macro( 133, data)
#define MREPEAT_ODD68( macro, data)     MREPEAT_ODD67( macro, data)   macro( 135, data)
#define MREPEAT_ODD69( macro, data)     MREPEAT_ODD68( macro, data)   macro( 137, data)
#define MREPEAT_ODD70( macro, data)     MREPEAT_ODD69( macro, data)   macro( 139, data)
#define MREPEAT_ODD71( macro, data)     MREPEAT_ODD70( macro, data)   macro( 141, data)
#define MREPEAT_ODD72( macro, data)     MREPEAT_ODD71( macro, data)   macro( 143, data)
#define MREPEAT_ODD73( macro, data)     MREPEAT_ODD72( macro, data)   macro( 145, data)
#define MREPEAT_ODD74( macro, data)     MREPEAT_ODD73( macro, data)   macro( 147, data)
#define MREPEAT_ODD75( macro, data)     MREPEAT_ODD74( macro, data)   macro( 149, data)
#define MREPEAT_ODD76( macro, data)     MREPEAT_ODD75( macro, data)   macro( 151, data)
#define MREPEAT_ODD77( macro, data)     MREPEAT_ODD76( macro, data)   macro( 153, data)
#define MREPEAT_ODD78( macro, data)     MREPEAT_ODD77( macro, data)   macro( 155, data)
#define MREPEAT_ODD79( macro, data)     MREPEAT_ODD78( macro, data)   macro( 157, data)
#define MREPEAT_ODD80( macro, data)     MREPEAT_ODD79( macro, data)   macro( 159, data)
#define MREPEAT_ODD81( macro, data)     MREPEAT_ODD80( macro, data)   macro( 161, data)
#define MREPEAT_ODD82( macro, data)     MREPEAT_ODD81( macro, data)   macro( 163, data)
#define MREPEAT_ODD83( macro, data)     MREPEAT_ODD82( macro, data)   macro( 165, data)
#define MREPEAT_ODD84( macro, data)     MREPEAT_ODD83( macro, data)   macro( 167, data)
#define MREPEAT_ODD85( macro, data)     MREPEAT_ODD84( macro, data)   macro( 169, data)
#define MREPEAT_ODD86( macro, data)     MREPEAT_ODD85( macro, data)   macro( 171, data)
#define MREPEAT_ODD87( macro, data)     MREPEAT_ODD86( macro, data)   macro( 173, data)
#define MREPEAT_ODD88( macro, data)     MREPEAT_ODD87( macro, data)   macro( 175, data)
#define MREPEAT_ODD89( macro, data)     MREPEAT_ODD88( macro, data)   macro( 177, data)
#define MREPEAT_ODD90( macro, data)     MREPEAT_ODD89( macro, data)   macro( 179, data)
#define MREPEAT_ODD91( macro, data)     MREPEAT_ODD90( macro, data)   macro( 181, data)
#define MREPEAT_ODD92( macro, data)     MREPEAT_ODD91( macro, data)   macro( 183, data)
#define MREPEAT_ODD93( macro, data)     MREPEAT_ODD92( macro, data)   macro( 185, data)
#define MREPEAT_ODD94( macro, data)     MREPEAT_ODD93( macro, data)   macro( 187, data)
#define MREPEAT_ODD95( macro, data)     MREPEAT_ODD94( macro, data)   macro( 189, data)
#define MREPEAT_ODD96( macro, data)     MREPEAT_ODD95( macro, data)   macro( 191, data)
#define MREPEAT_ODD97( macro, data)     MREPEAT_ODD96( macro, data)   macro( 193, data)
#define MREPEAT_ODD98( macro, data)     MREPEAT_ODD97( macro, data)   macro( 195, data)
#define MREPEAT_ODD99( macro, data)     MREPEAT_ODD98( macro, data)   macro( 197, data)
#define MREPEAT_ODD100(macro, data)     MREPEAT_ODD99( macro, data)   macro( 199, data)
#define MREPEAT_ODD101(macro, data)     MREPEAT_ODD100(macro, data)   macro(201, data)
#define MREPEAT_ODD102(macro, data)     MREPEAT_ODD101(macro, data)   macro(203, data)
#define MREPEAT_ODD103(macro, data)     MREPEAT_ODD102(macro, data)   macro(205, data)
#define MREPEAT_ODD104(macro, data)     MREPEAT_ODD103(macro, data)   macro(207, data)
#define MREPEAT_ODD105(macro, data)     MREPEAT_ODD104(macro, data)   macro(209, data)
#define MREPEAT_ODD106(macro, data)     MREPEAT_ODD105(macro, data)   macro(211, data)
#define MREPEAT_ODD107(macro, data)     MREPEAT_ODD106(macro, data)   macro(213, data)
#define MREPEAT_ODD108(macro, data)     MREPEAT_ODD107(macro, data)   macro(215, data)
#define MREPEAT_ODD109(macro, data)     MREPEAT_ODD108(macro, data)   macro(217, data)
#define MREPEAT_ODD110(macro, data)     MREPEAT_ODD109(macro, data)   macro(219, data)
#define MREPEAT_ODD111(macro, data)     MREPEAT_ODD110(macro, data)   macro(221, data)
#define MREPEAT_ODD112(macro, data)     MREPEAT_ODD111(macro, data)   macro(223, data)
#define MREPEAT_ODD113(macro, data)     MREPEAT_ODD112(macro, data)   macro(225, data)
#define MREPEAT_ODD114(macro, data)     MREPEAT_ODD113(macro, data)   macro(227, data)
#define MREPEAT_ODD115(macro, data)     MREPEAT_ODD114(macro, data)   macro(229, data)
#define MREPEAT_ODD116(macro, data)     MREPEAT_ODD115(macro, data)   macro(231, data)
#define MREPEAT_ODD117(macro, data)     MREPEAT_ODD116(macro, data)   macro(233, data)
#define MREPEAT_ODD118(macro, data)     MREPEAT_ODD117(macro, data)   macro(235, data)
#define MREPEAT_ODD119(macro, data)     MREPEAT_ODD118(macro, data)   macro(237, data)
#define MREPEAT_ODD120(macro, data)     MREPEAT_ODD119(macro, data)   macro(239, data)
#define MREPEAT_ODD121(macro, data)     MREPEAT_ODD120(macro, data)   macro(241, data)
#define MREPEAT_ODD122(macro, data)     MREPEAT_ODD121(macro, data)   macro(243, data)
#define MREPEAT_ODD123(macro, data)     MREPEAT_ODD122(macro, data)   macro(245, data)
#define MREPEAT_ODD124(macro, data)     MREPEAT_ODD123(macro, data)   macro(247, data)
#define MREPEAT_ODD125(macro, data)     MREPEAT_ODD124(macro, data)   macro(249, data)
#define MREPEAT_ODD126(macro, data)     MREPEAT_ODD125(macro, data)   macro(251, data)
#define MREPEAT_ODD127(macro, data)     MREPEAT_ODD126(macro, data)   macro(253, data)
#define MREPEAT_ODD128(macro, data)     MREPEAT_ODD127(macro, data)   macro(255, data)

#endif  // _MREPEAT_H_
